# nao usada pois a nossa conta estudante nao tem acesso ao azure container registry


#trigger:
#  - main
#
#pool:
#  vmImage: ubuntu-latest
#
#steps:
#  # 1. Run tests
#  - task: Maven@4
#    inputs:
#      mavenPomFile: 'pom.xml'
#      goals: 'clean verify'
#    displayName: 'Run Maven tests'
#
#  # 2. Build Docker image
#  - task: DockerCompose@0
#    displayName: 'Build Docker image'
#    inputs:
#      containerregistrytype: 'Azure Container Registry'
#      azureSubscription: '<your-service-connection>'
#      azureContainerRegistry: '<yourregistry>.azurecr.io'
#      dockerComposeFile: '**/docker-compose.yml'
#      action: 'Run a Docker Compose command'
#      command: 'build'
#
#  # 3. Push image
#  - task: DockerCompose@0
#    displayName: 'Push Docker image to ACR'
#    inputs:
#      containerregistrytype: 'Azure Container Registry'
#      azureSubscription: '<your-service-connection>'
#      azureContainerRegistry: '<yourregistry>.azurecr.io'
#      dockerComposeFile: '**/docker-compose.yml'
#      action: 'Run a Docker Compose command'
#      command: 'push'
#
#  # 4. Deploy to Azure App Service (example)
#  - task: AzureWebApp@1
#    displayName: 'Deploy to Azure App Service'
#    inputs:
#      azureSubscription: '<your-service-connection>'
#      appName: '<your-app-service-name>'
#      images: '<yourregistry>.azurecr.io/reciclagem-api:latest'
