trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: 'reciclagem-app'
  azureServiceConnection: 'Azure for Students (24e40e5e-6a9a-4863-9ec5-372dd1374a1c)'
  dockerImageName: 'reciclagem-app-image'

steps:
  # Maven build + test
  - task: Maven@4
    displayName: 'Run Maven tests'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  #  Build Docker image
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(dockerImageName):$(Build.BuildId)

  # Deploy Docker image directly to Azure App Service (no ACR)
  - task: AzureWebAppContainer@1
    displayName: 'Deploy to Azure Web App for Containers'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      appName: '$(appName)'
      containers: |
        $(dockerImageName):$(Build.BuildId)
