version: '3.8'  # Define a versão do Compose, compatível com recursos modernos

services:
  db:  # Serviço de banco de dados
    container_name: mysql  # Nome do container (opcional)
    image: mysql:8.0  # Imagem oficial do MySQL
    ports:
      - "3306:3306"  # Expõe a porta padrão do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root_pass  # Senha do usuário root
      MYSQL_DATABASE: api             # Cria o banco de dados "api"
    volumes:
      - db_data:/var/lib/mysql  # Volume para persistir os dados do banco
    healthcheck:  # Verifica se o banco está pronto antes de subir a API
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:  # Serviço da aplicação
    build: .  # Usa o Dockerfile no diretório atual
    ports:
      - "8080:8080"  # Mapeia a porta da aplicação
    depends_on:  # Aguarda o banco de dados estar saudável
      db:
        condition: service_healthy
    environment:
      - PROFILE=dev  # Define o perfil da aplicação
      - DATABASE_URL=jdbc:mysql://db:3306/api?createDatabaseIfNotExist=true  # URL de conexão com o banco
      - DATABASE_USER=root  # Usuário do banco
      - DATABASE_PWD=root_pass  # Senha do banco

volumes:
  db_data:  # Volume nomeado para persistência dos dados do MySQL