name: CI-CD Pipeline
run-name: ${{ github.actor }} está rodando a nova pipeline.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # MySQL for integration tests
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_pass
          MYSQL_DATABASE: api
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2️⃣ Set up Java (Maven)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Run Maven unit tests
      - name: Run Maven unit tests
        run: mvn clean verify -DskipITs=false

      # 4️⃣ Build Docker image (local, just for testing)
      - name: Build Docker image
        run: docker build -t reciclagem-app:${{ github.sha }} .


